### ISSUE TITLE
when I run the install.sh,have error

### ISSUE THREAD

**Issue by yhl5555** [LevyHsu/CF-Cannon#4]
Collecting demjson
  Using cached demjson-2.2.4.tar.gz (131 kB)
Collecting Flask
  Using cached Flask-1.1.1-py2.py3-none-any.whl (94 kB)
Collecting pycurl
  Using cached pycurl-7.43.0.5.tar.gz (216 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-FWn3Og/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-FWn3Og/pycurl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-FWn3Og/pycurl/pip-egg-info
         cwd: /tmp/pip-install-FWn3Og/pycurl/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-FWn3Og/pycurl/setup.py", line 961, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-FWn3Og/pycurl/setup.py", line 623, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-FWn3Og/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-FWn3Og/pycurl/setup.py", line 238, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LevyHsu** [comment]
Try manually install pycurl and check the integrity of your pip
